### ISSUE TITLE
fontello open returning 301 redirect error after rails update

### ISSUE THREAD

**Issue by EddieOne** [railslove/fontello_rails_converter#51]
# fontello open
---- open ----
Traceback (most recent call last):
	13: from /root/.rbenv/versions/2.6.6/bin/fontello:23:in `<main>'
	12: from /root/.rbenv/versions/2.6.6/bin/fontello:23:in `load'
	11: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontello_rails_converter-0.4.6/bin/fontello:138:in `<top (required)>'
	10: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontello_rails_converter-0.4.6/lib/fontello_rails_converter/cli.rb:17:in `open'
	 9: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontello_rails_converter-0.4.6/lib/fontello_rails_converter/fontello_api.rb:16:in `new_session_from_config'
	 8: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'
	 7: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	 6: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	 5: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	 4: from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:920:in `start'
	 3: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	 2: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	 1: from /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:123:in `return!'
/root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 301 Moved Permanently (RestClient::MovedPermanently)

**Comment by duleorlovic** [comment]
This was fixed #50 on master branch but not yet released.
You can try using github instead rubygems
```
# Gemfile
gem 'fontello_rails_converter', github: 'railslove/fontello_rails_converter'
```
